Fixed some spacing.

diff --git a/blog_module b/blog_module
--- a/blog_module
+++ b/blog_module
@@ -7,62 +7,62 @@
 
 
 function validate__entry_number() {
-        if [ "$entry_number" == "all" ] || [ "$entry_number" == "last" ]; then
-                # Nothing needs to be done.
-                :
-        elif [[ "$entry_number" =~ ^[0-9]+$ ]]; then
-                # Nothing needs to be done.
-                :
-        elif [[ "$entry_number" =~ ^([0-9]+,[ ]?)+[0-9]+$ ]]; then
-                # Nothing needs to be done.
-                :
-        else
-                echo "Your entry is invalid."
-                echo "   blog help   if you're unsure how to proceed."
-                exit 1
-        fi
+    if [ "$entry_number" == "all" ] || [ "$entry_number" == "last" ]; then
+            # Nothing needs to be done.
+            :
+    elif [[ "$entry_number" =~ ^[0-9]+$ ]]; then
+            # Nothing needs to be done.
+            :
+    elif [[ "$entry_number" =~ ^([0-9]+,[ ]?)+[0-9]+$ ]]; then
+            # Nothing needs to be done.
+            :
+    else
+            echo "Your entry is invalid."
+            echo "   blog help   if you're unsure how to proceed."
+            exit 1
+    fi
 }
 
 function validate__mysql_output() {
-        if [ "$mysql_output" == "" ]; then
-                if [ singular_check__entry_number == "True" ]; then
-                        echo "That entry doesn't exist."
-                        exit 1
-                else
-                        echo "Those entries don't exist."
-                        exit 1
-                fi
-        fi
+    if [ "$mysql_output" == "" ]; then
+            if [ singular_check__entry_number == "True" ]; then
+                    echo "That entry doesn't exist."
+                    exit 1
+            else
+                    echo "Those entries don't exist."
+                    exit 1
+            fi
+    fi
 }
 
 function validate__entry_exists() {
-        output="$(blog read -e "$entry_number")"
-        if [[ ! "$output" =~ [^[:space:]] ]]; then
-                if [ singular_check__entry_number == "True" ]; then
-                        echo "That entry doesn't exist."
-                        exit 1
-                else
-                        echo "Those entries don't exist."
-                        exit 1
-                fi
-        fi
+    output="$(blog read -e "$entry_number")"
+    if [[ ! "$output" =~ [^[:space:]] ]]; then
+            if [ singular_check__entry_number == "True" ]; then
+                    echo "That entry doesn't exist."
+                    exit 1
+            else
+                    echo "Those entries don't exist."
+                    exit 1
+            fi
+    fi
 }
 
 function options_check__entry_number() {
-        if [ "$entry_number" == "" ]; then
-                prompt_user__set_entry_number
-        fi
+    if [ "$entry_number" == "" ]; then
+            prompt_user__set_entry_number
+    fi
 }
 
 function options_check__file_name() {
-        desired_name="$1"
-        if [ "$file_name" == "" ]; then
-                if [ "$desired_name" == "" ]; then
-                        file_name="./entry"
-                else
-                        file_name="$desired_name"
-                fi
-        fi
+    desired_name="$1"
+    if [ "$file_name" == "" ]; then
+            if [ "$desired_name" == "" ]; then
+                file_name="./entry"
+            else
+                    file_name="$desired_name"
+            fi
+    fi
 }
 
 
@@ -84,7 +84,7 @@ function format_entry() {
 
 
 function clean_output() {
-        output="$1"	
+    output="$1"	
 	# Removes some cluttery output from the MySQL output.
 	output="$(echo -e "$output" | grep -v '^[-]*$')"
 	# Handles different output fields to make things more visibly pleasant.
@@ -92,7 +92,7 @@ function clean_output() {
 	# Removes the header displaying the fields outputted by MySQL.
 	output="$(echo -e "$output" | sed '1d')"
 
-        echo -e "$output"
+	echo -e "$output"
 }
 
 
@@ -102,20 +102,20 @@ function clean_output() {
 
 
 function output_to_user() {
-        echo " "
-        echo -e "$(echo -e "$mysql_output" | fold -s -w $(tput cols))"
-        echo " "
+    echo " "
+    echo -e "$(echo -e "$mysql_output" | fold -s -w $(tput cols))"
+    echo " "
 }
 
 function display_output() {
-        if [ "$style" == "user" ]; then
-                output_to_user
-        elif [ "$style" == "system" ]; then
-                echo -e "$mysql_output"
-        else
-                echo "Something went wrong."
-                exit 1
-        fi
+    if [ "$style" == "user" ]; then
+        output_to_user
+    elif [ "$style" == "system" ]; then
+        echo -e "$mysql_output"
+    else
+        echo "Something went wrong."
+        exit 1
+    fi
 }
  
 
@@ -125,20 +125,20 @@ function display_output() {
 
 
 function write_to_database() {
-        formatted_entry=$(format_entry)
+    formatted_entry=$(format_entry)
 	echo "$formatted_entry"
-        loaded_sql=$(get_sql "$formatted_entry")
-        execute_sql "$loaded_sql"
+    loaded_sql=$(get_sql "$formatted_entry")
+    execute_sql "$loaded_sql"
 }
 
 function read_from_database() {
-        loaded_sql=$(get_sql)
-        execute_sql "$loaded_sql"
+    loaded_sql=$(get_sql)
+    execute_sql "$loaded_sql"
 }
 
 function delete_from_database() {
-        loaded_sql=$(get_sql)
-        execute_sql "$loaded_sql"
+    loaded_sql=$(get_sql)
+    execute_sql "$loaded_sql"
 }
 
 
@@ -148,55 +148,54 @@ function delete_from_database() {
 
 
 function execute_sql() {
-        DATABASE_NAME="blog_entries"
-        CONTAINER_NAME="mysql_blog_interface"
-        MYSQL_CONFIG_PATH="/usr/local/share/blog_config_mysql.cnf"
-        BLOG_CONFIG_PATH="/usr/local/share/blog_config.yml"
-        in_container=$(get_value_from_key "Container")
-        sql="$1"
+    DATABASE_NAME="blog_entries"
+    CONTAINER_NAME="mysql_blog_interface"
+    MYSQL_CONFIG_PATH="/usr/local/share/blog_config_mysql.cnf"
+    BLOG_CONFIG_PATH="/usr/local/share/blog_config.yml"
+    in_container=$(get_value_from_key "Container")
+    sql="$1"
         
 	# Determines whether the client is being run inside or outside the container, then:
-        # Enters the DBMS, submits the query, and places the data in "output".
-        case "$in_container" in
-                True)
-                        output_dirty=$(mysql --defaults-extra-file="$MYSQL_CONFIG_PATH" -D "$DATABASE_NAME" -e "$sql")
-                        mysql_err="$?"
+    # Enters the DBMS, submits the query, and places the data in "output".
+    case "$in_container" in
+        True)
+            output_dirty=$(mysql --defaults-extra-file="$MYSQL_CONFIG_PATH" -D "$DATABASE_NAME" -e "$sql")
+            mysql_err="$?"
 			;;
-                False)
-                        output_dirty=$(docker-compose exec "$CONTAINER_NAME" mysql --defaults-extra-file="$MYSQL_CONFIG_PATH" -D "$DATABASE_NAME" -e "$sql")
-                        mysql_err=$(docker-compose exec "$CONTAINER_NAME" echo "$?")
-                        ;;
-                "" | *)
-                        echo "You must have a \"Container: [True] | [False]\" configuration in "$BLOG_CONFIG_PATH""
-                        exit 1
-                        ;;
-        esac
-        # Returns cleaned output and the MySQL exit code.
-        
+        False)
+            output_dirty=$(docker-compose exec "$CONTAINER_NAME" mysql --defaults-extra-file="$MYSQL_CONFIG_PATH" -D "$DATABASE_NAME" -e "$sql")
+            mysql_err=$(docker-compose exec "$CONTAINER_NAME" echo "$?")
+            ;;
+        "" | *)
+            echo "You must have a \"Container: [True] | [False]\" configuration in "$BLOG_CONFIG_PATH""
+            exit 1
+            ;;
+    esac
+           
 	mysql_output=$(clean_output "$output_dirty")	
 }
 
 function execute_backup() {
-        DATABASE_NAME="blog_entries"
-        CONTAINER_NAME="mysql_blog_interface"
-        MYSQL_CONFIG_PATH="/usr/local/share/blog_config_mysql.cnf"
-        BLOG_CONFIG_PATH="/usr/local/share/blog_config.yml"
-        in_container=$(get_value_from_key "Container")
+    DATABASE_NAME="blog_entries"
+    CONTAINER_NAME="mysql_blog_interface"
+    MYSQL_CONFIG_PATH="/usr/local/share/blog_config_mysql.cnf"
+    BLOG_CONFIG_PATH="/usr/local/share/blog_config.yml"
+    in_container=$(get_value_from_key "Container")
 
-        case "$in_container" in
-                True)
-                        mysqldump --defaults-extra-file="$MYSQL_CONFIG_PATH" --default-character-set=utf8 "$DATABASE_NAME" > "$file_name"
-                        mysql_err="$?"
-                        ;;
-                False)
-                        docker-compose exec "$CONTAINER_NAME" mysqldump --defaults-extra-file="$MYSQL_CONFIG_PATH" --default-character-set=utf8 "$DATABASE_NAME" > "$file_name"
-                        mysql_err="$(docker-compose exec "$CONTAINER_NAME" echo "$?")"
-                        ;;
-                "" | *)
-                        echo "You must have a \"Container: [True] | [False]\" configuration in "$BLOG_CONFIG_PATH""
-                        exit 1
-                        ;;
-        esac
+    case "$in_container" in
+        True)
+            mysqldump --defaults-extra-file="$MYSQL_CONFIG_PATH" --default-character-set=utf8 "$DATABASE_NAME" > "$file_name"
+            mysql_err="$?"
+            ;;
+        False)
+            docker-compose exec "$CONTAINER_NAME" mysqldump --defaults-extra-file="$MYSQL_CONFIG_PATH" --default-character-set=utf8 "$DATABASE_NAME" > "$file_name"
+            mysql_err="$(docker-compose exec "$CONTAINER_NAME" echo "$?")"
+            ;;
+        "" | *)
+            echo "You must have a \"Container: [True] | [False]\" configuration in "$BLOG_CONFIG_PATH""
+            exit 1
+            ;;
+    esac
 }
 
 
@@ -207,21 +206,21 @@ function execute_backup() {
 
 function prompt_user__write_entry() {
 	truncate -s 0 "$file_name"
-        vim +"set wrap linebreak" -c "startinsert" "$file_name"
+    vim +"set wrap linebreak" -c "startinsert" "$file_name"
 }
 
 function prompt_user__read_last_entry() {
-        echo "Read last entry?: (y/N)"
-        read read_ans
+    echo "Read last entry?: (y/N)"
+    read read_ans
 
-        if [ "$read_ans" != "Y" ] && [ "$read_ans" != "y" ]; then
-                exit 0
-        fi
+    if [ "$read_ans" != "Y" ] && [ "$read_ans" != "y" ]; then
+        exit 0
+    fi
 }
 
 function prompt_user__confirm_write() {
 	echo "Are you sure you want to submit this entry? (y/N)"
-        read write_ans
+    read write_ans
 	if [ "$write_ans" != "Y" ] && [ "$write_ans" != "y" ]; then
 		echo "Your entry has not been submitted."
 		exit 0
@@ -231,14 +230,14 @@ function prompt_user__confirm_write() {
 function prompt_user__edit_entry() {
 	entry="$1"
 	echo "$entry" > "$file_name"
-        vim +"set wrap linebreak" -c "startinsert" "$file_name"
+    vim +"set wrap linebreak" -c "startinsert" "$file_name"
 }
 
 function prompt_user__confirm_edit() {
 	echo "Are you sure you want to permanently overwrite this entry? (y/N)"
-        read edit_ans
+    read edit_ans
 	if [ "$edit_ans" != "Y" ] && [ "$edit_ans" != "y" ]; then
-      		echo "Nothing has been overwritten."
+  		echo "Nothing has been overwritten."
 		exit 0
 	fi
 }
@@ -253,14 +252,14 @@ function prompt_user__confirm_read_edited() {
 
 function prompt_user__confirm_deletion() {
 	if [ singular_check__entry_number == "True" ]; then
-                echo "Are you sure you want to permanently delete that entry? (y/N)"
-        else
-                echo "Are you sure you want to permanently delete those entries? (y/N)"
-        fi
+        echo "Are you sure you want to permanently delete that entry? (y/N)"
+    else
+        echo "Are you sure you want to permanently delete those entries? (y/N)"
+    fi
 
-        read del_ans
+    read del_ans
 
-      	if [ $del_ans != "Y" ] && [ $del_ans != "y" ]; then
+  	if [ $del_ans != "Y" ] && [ $del_ans != "y" ]; then
 		echo "Nothing was deleted."
 		exit 0
 	fi
@@ -268,56 +267,56 @@ function prompt_user__confirm_deletion() {
 
 function prompt_user__read_all() {
 	echo "Read all entries? (y/N)"
-        read read_ans
-       	if [ "$read_ans" != "Y" ] && [ "$read_ans" != "y" ]; then
+    read read_ans
+    if [ "$read_ans" != "Y" ] && [ "$read_ans" != "y" ]; then
 		exit 0
 	fi
 }
 
 function prompt_user__set_entry_number() {
-        case "$action" in
-                read)
-                        echo "Which entries would you like to read?"
-                        echo -e "\tex) 5"
-                        echo -e "\tex) 2, 4, 5"
-                        echo -e "\tex) last"
-                        echo -e "\tex) all"
-                        read entry_number
-                        ;;
-                edit)
-                        echo "Which entry would you like to overwrite?"
-                        echo -e "\tex) 5"
-                        echo -e "\tex)last"
-                        read entry_number
-                        ;;
-                delete)
-                        echo "Which entries would you like to delete?"
-                        echo -e "\tex) 5"
-                        echo -e "\tex) 2, 4, 5"
-                        echo -e "\tex) last"
-                        read entry_number
-                        ;;
-        esac
+    case "$action" in
+        read)
+            echo "Which entries would you like to read?"
+            echo -e "\tex) 5"
+            echo -e "\tex) 2, 4, 5"
+            echo -e "\tex) last"
+            echo -e "\tex) all"
+            read entry_number
+            ;;
+        edit)
+            echo "Which entry would you like to overwrite?"
+            echo -e "\tex) 5"
+            echo -e "\tex)last"
+            read entry_number
+            ;;
+        delete)
+            echo "Which entries would you like to delete?"
+            echo -e "\tex) 5"
+            echo -e "\tex) 2, 4, 5"
+            echo -e "\tex) last"
+            read entry_number
+            ;;
+    esac
 }
 
 function prompt_user__help() {
 	echo "Actions:"
-        echo -e "\tread"
-        echo -e "\twrite"
-        echo -e "\tedit"
-        echo -e "\tdelete"
-        echo -e "\tbackup"
-        echo -e "\thelp"
-        echo " "
-        echo "Options:"
-        echo -e "\t[-e entry_number]"
-        echo -e "\t[-f file_name]"
-        echo " "
-        echo "Examples:"
-        echo -e "\tblog read -e all"
-        echo -e "\tblog write -f prewritten_entry.txt"
-        echo -e "\tblog edit -e 6 -f file_to_work_in.txt"
-        echo -e "\tblog delete -e last"
+    echo -e "\tread"
+    echo -e "\twrite"
+    echo -e "\tedit"
+    echo -e "\tdelete"
+    echo -e "\tbackup"
+    echo -e "\thelp"
+    echo " "
+    echo "Options:"
+    echo -e "\t[-e entry_number]"
+    echo -e "\t[-f file_name]"
+    echo " "
+    echo "Examples:"
+    echo -e "\tblog read -e all"
+    echo -e "\tblog write -f prewritten_entry.txt"
+    echo -e "\tblog edit -e 6 -f file_to_work_in.txt"
+    echo -e "\tblog delete -e last"
 }
 
 #---------------------------------------------------------------------------------------------
@@ -326,28 +325,28 @@ function prompt_user__help() {
 
 
 function error_check__mysql() {
-        if [ "$mysql_err" != 0 ]; then
-                echo "Something went wrong."
-                exit 1
-        fi
+    if [ "$mysql_err" != 0 ]; then
+        echo "Something went wrong."
+        exit 1
+    fi
 }
 
 
 function singular_check__entry_number() {
-        if [ echo "$(echo "$entry_number" | grep -oE '[0-9]+' | wc -l)" -eq 1 ]; then
-                echo "True"
-        else
-                echo "False"
-        fi
+    if [ echo "$(echo "$entry_number" | grep -oE '[0-9]+' | wc -l)" -eq 1 ]; then
+        echo "True"
+    else
+        echo "False"
+    fi
 }
 
 function get_value_from_key() {
-        CONFIG_PATH="/usr/local/share/blog_config.yml"
-        key_to_check="$1"
-        key_line=$(echo "$(<"$CONFIG_PATH")" | sed -n "/$key_to_check:\s/p")
-        value=$(echo "$key_line" | sed -r "s/$key_to_check:\s//g")
+    CONFIG_PATH="/usr/local/share/blog_config.yml"
+    key_to_check="$1"
+    key_line=$(echo "$(<"$CONFIG_PATH")" | sed -n "/$key_to_check:\s/p")
+    value=$(echo "$key_line" | sed -r "s/$key_to_check:\s//g")
 
-        echo "$value"
+    echo "$value"
 }
 
 
@@ -358,20 +357,19 @@ function get_value_from_key() {
 
 # This function was built to help facilitate development.
 function local_publish() {
-        # Moves necessary files to a $PATH directory for ease of access.
-        cp blog /usr/local/bin/blog
-        cp blog_module /usr/local/bin/blog_module
-        cp blog_sql /usr/local/bin/blog_sql
-
-        # Report results to user.
-        if [ "$?" -eq 0 ]; then
-                echo "Publish to /usr/local/bin successful."
-                echo "You may now run commands using:"
-                echo -e "\tblog ..."
-        else
-                echo "Something went wrong."
-                exit 1
-        fi
+    # Moves necessary files to a $PATH directory for ease of access.
+    cp blog /usr/local/bin/blog
+    cp blog_module /usr/local/bin/blog_module
+    cp blog_sql /usr/local/bin/blog_sql
+    # Report results to user.
+    if [ "$?" -eq 0 ]; then
+        echo "Publish to /usr/local/bin successful."
+        echo "You may now run commands using:"
+        echo -e "\tblog ..."
+    else
+        echo "Something went wrong."
+        exit 1
+    fi
 }
 
 function debug() {
