Changed error logic so that errors are usually handled early.

diff --git a/blog_module b/blog_module
--- a/blog_module
+++ b/blog_module
@@ -221,8 +221,12 @@ function blog_write() {
 
 
 	# Report results to the user, show a finalized version of their write if requested.
-        if [ "$mysql_err" ==  0 ]; then
+        if [ "$mysql_err" !=  0 ]; then
+	
+		echo "Something went wrong."
+                exit 1
 
+	else
                 echo "Write successful."
                 echo "Read last entry?: (Y/N)"
                 read read_ans
@@ -235,9 +239,6 @@ function blog_write() {
                 else
 			exit 0
                 fi
-        else
-                echo "Something went wrong."
-		exit 1
         fi
 }
 
@@ -266,9 +267,12 @@ function blog_edit() {
 	output=$(blog read "$edit_num" "clean")
 
 	if [ "$output" == "" ]; then
+
 		echo "That entry doesn't exist."
 		exit 1
+
 	else
+
 		# Allows the user to edit the entry.
 		echo "$output" > "$file_name"
 		vim "$file_name"
@@ -278,8 +282,13 @@ function blog_edit() {
         	read edit_ans
 
 		# Executes the SQL in the DBMS, report results to user, display all entries if requested.
-        	if [ $edit_ans == "Y" ] || [ $edit_ans == "y" ]; then
+        	if [ $edit_ans != "Y" ] && [ $edit_ans != "y" ]; then
          	
+			echo "Nothing has been overwritten."
+                        exit 0
+
+		else
+
 	 		# Prep entry file by formatting for MySQL and determine SQL to be used.
         		ENTRY_FILE=$(prep_entry "$file_name")
         		mysql_action=$(sql "$action" "$edit_num" "$ENTRY_FILE")	
@@ -287,7 +296,11 @@ function blog_edit() {
         		mysql_err="${output_and_err%% *}"
         		output="${output_and_err#* }"
 
-               		if [ "$mysql_err" == "0" ]; then
+               		if [ "$mysql_err" != "0" ]; then
+
+				echo "Something went wrong. Nothing has been overwritten."
+                                exit 1
+			else
                        		echo "Read your edited entry? (Y/N)"
                         	read read_ans
 
@@ -299,14 +312,8 @@ function blog_edit() {
                         	else
 					exit 0
                         	fi
-                	else
-                        	echo "Something went wrong. Nothing has been overwritten."
-				exit 1
                 	fi
-        	else
-                	echo "Nothing has been overwritten."
-			exit 0
-        	fi
+		fi
 	fi
 }
 
@@ -325,7 +332,7 @@ function blog_delete() {
 
 	# Checks if the entry exists, informs user, and performs a plural check.
 	output="$(blog read "$del_nums")"
-	if [[ ! "$output" =~ [^[:space:]] ]]; then
+	if [[ ! "$output" =~ [^[:space:]] ]]; then	# Looks for anything except white space.
 		if [ $(echo "$del_nums" | grep -oE '[0-9]+' | wc -l) -eq 1 ]; then
                 	echo "That entry doesn't exist."
        		else
@@ -390,7 +397,7 @@ function blog_backup() {
 
         AFTER_DUMP=$(<backup.sql)
 
-	# Checks if the snapshots are different to determine success.
+	# Checks MySQL exit code & if the snapshots are different to determine success.
         if [ "$BEFORE_DUMP" != "$AFTER_DUMP" ] && [ "$mysql_err" == "0" ]; then
                 echo "Backup successful."
 		exit 0
@@ -408,7 +415,7 @@ function local_publish() {
         cp blog /usr/local/bin/blog
 
 	# Report results to user.
-        if [ $? -eq 0 ]; then
+        if [ "$?" -eq 0 ]; then
                 echo -e "Publish to /usr/local/bin successful.\nYou may now run commands using:\n\tblog ..."
                 cleanup
 		exit 0
